const WA_LINK = `https://wa.me/254700000000?text=Hello%20Moffat%20Tech!%20I%27d%20like%20a%20free%20quote.`;

const CONTACTS = [
  { icon: '📍', label: 'Nairobi, Kenya'           },
    { icon: '📞', label: '+254 700 000 000', href: 'tel:+254700000000'              },
      { icon: '✉️', label: 'info@moffattech.co.ke', href: 'mailto:info@moffattech.co.ke' },
        { icon: '⏰', label: 'Mon–Sat, 7am – 6pm'       },
        ];

        export default function ContactCTA() {
          return (
              <section id="contact" style={{ padding: '80px 0', background: 'var(--dark-2)', position: 'relative', overflow: 'hidden' }}>
                    <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(ellipse 70% 80% at 50% 50%,rgba(245,196,0,.08),transparent)' }} />
                          <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 20px', textAlign: 'center', position: 'relative', zIndex: 1 }}>

                                  <div style={{ fontSize: 12, fontFamily: 'var(--fh)', fontWeight: 700, letterSpacing: 4, textTransform: 'uppercase', color: 'var(--yellow)', marginBottom: 12 }}>Get Started Today</div>
                                          <h2 style={{ fontFamily: 'var(--fh)', fontSize: 'clamp(36px,6vw,60px)', fontWeight: 800, textTransform: 'uppercase', lineHeight: 1.05 }}>
                                                    Ready To Power<br /><span style={{ color: 'var(--yellow)' }}>Your Project?</span>
                                                            </h2>
                                                                    <p style={{ color: 'var(--gray-light)', fontSize: 16, fontWeight: 300, maxWidth: 520, margin: '16px auto 40px' }}>
                                                                              Get a free consultation and quote. We serve Nairobi, Kiambu, Mombasa and all of Kenya.
                                                                                      </p>

                                                                                              <div style={{ display: 'flex', justifyContent: 'center', gap: 16, flexWrap: 'wrap' }}>
                                                                                                        <a href={WA_LINK} target="_blank" rel="noreferrer" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '14px 28px', borderRadius: 12, background: 'var(--yellow)', color: 'var(--dark)', fontFamily: 'var(--fh)', fontWeight: 700, fontSize: 16, textTransform: 'uppercase', textDecoration: 'none' }}>
                                                                                                                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor">
                                                                                                                                  <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z" />
                                                                                                                                              </svg>
                                                                                                                                                          WhatsApp Us Now
                                                                                                                                                                    </a>
                                                                                                                                                                              <a href="tel:+254700000000" style={{ display: 'inline-flex', alignItems: 'center', gap: 8, padding: '14px 28px', borderRadius: 12, background: 'transparent', color: 'var(--white)', border: '1.5px solid rgba(255,255,255,.25)', fontFamily: 'var(--fh)', fontWeight: 700, fontSize: 16, textTransform: 'uppercase', textDecoration: 'none' }}>
                                                                                                                                                                                          📞 Call Us
                                                                                                                                                                                                    </a>
                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                    <div style={{ display: 'flex', justifyContent: 'center', gap: 32, marginTop: 48, flexWrap: 'wrap' }}>
                                                                                                                                                                                                                              {CONTACTS.map(c => (
                                                                                                                                                                                                                                          <a key={c.label} href={c.href || '#'} style={{ display: 'flex', alignItems: 'center', gap: 12, fontSize: 14, color: 'var(--gray-light)', textDecoration: 'none' }}>
                                                                                                                                                                                                                                                        <div style={{ width: 40, height: 40, borderRadius: 10, background: 'rgba(255,255,255,.06)', border: '1px solid rgba(255,255,255,.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16 }}>{c.icon}</div>
                                                                                                                                                                                                                                                                      {c.label}
                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                