const SVC  = ['Electrical Installation','Solar Panel Systems','Solar Maintenance','Industrial Electrical','Energy Audits','Safety & Protection'];
const COMP = ['About Us','Our Process','Reviews','Contact','Careers','Projects Gallery'];
const INFO = [
  { label: '+254 700 000 000',      href: 'tel:+254700000000'               },
    { label: 'info@moffattech.co.ke', href: 'mailto:info@moffattech.co.ke'    },
      { label: 'Nairobi, Kenya'                                                  },
        { label: 'Mon–Sat: 7am – 6pm'                                             },
          { label: 'Emergency: 24/7'                                                 },
          ];

          export default function Footer() {
            return (
                <>
                      <style>{`
                              .foot-grid { display: grid; grid-template-columns: 2fr 1fr 1fr 1fr; gap: 48px; }
                                      .flink { font-size:14px; color:var(--gray); display:block; margin-bottom:10px; text-decoration:none; transition:color .2s; }
                                              .flink:hover { color: var(--yellow); }
                                                      @media (max-width: 1024px) { .foot-grid { grid-template-columns: 1fr 1fr !important; } }
                                                              @media (max-width: 600px)  { .foot-grid { grid-template-columns: 1fr !important; } }
                                                                    `}</style>
                                                                          <footer style={{ background: 'var(--dark)', borderTop: '1px solid rgba(255,255,255,.06)', padding: '60px 0 30px' }}>
                                                                                  <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 20px' }}>

                                                                                            <div className="foot-grid" style={{ paddingBottom: 48, borderBottom: '1px solid rgba(255,255,255,.06)' }}>

                                                                                                        {/* Brand */}
                                                                                                                    <div>
                                                                                                                                  <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
                                                                                                                                                  <div style={{ width: 42, height: 42, background: 'var(--yellow)', borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                                                                                                                                                    <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#0A0E17" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                                                                                                                                                                                        <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
                                                                                                                                                                                                          </svg>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                          <div style={{ fontFamily: 'var(--fh)' }}>
                                                                                                                                                                                                                                                            <div style={{ fontSize: 20, fontWeight: 800 }}>MOFFAT <span style={{ color: 'var(--yellow)' }}>TECH</span></div>
                                                                                                                                                                                                                                                                              <div style={{ fontSize: 10, color: 'var(--gray)', letterSpacing: 2, textTransform: 'uppercase' }}>Electrical & Solar Engineering</div>
                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                          <p style={{ color: 'var(--gray)', fontSize: 14, lineHeight: 1.7, marginBottom: 24 }}>
                                                                                                                                                                                                                                                                                                                                          Empowering homes and businesses across Kenya with reliable electrical and sustainable solar solutions since 2014.
                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', gap: 12 }}>
                                                                                                                                                                                                                                                                                                                                                                                      {['f','in','tw','wa'].map(s => (
                                                                                                                                                                                                                                                                                                                                                                                                        <div key={s} style={{ width: 38, height: 38, borderRadius: 10, background: 'rgba(255,255,255,.06)', border: '1px solid rgba(255,255,255,.1)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontFamily: 'var(--fh)', fontWeight: 700, textTransform: 'uppercase', cursor: 'pointer', transition: 'all .2s' }}
                                                                                                                                                                                                                                                                                                                                                                                                                            onMouseEnter={e => { e.currentTarget.style.background = 'var(--yellow)'; e.currentTarget.style.color = 'var(--dark)'; }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                onMouseLeave={e => { e.currentTarget.style.background = 'rgba(255,255,255,.06)'; e.currentTarget.style.color = 'var(--white)'; }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >{s}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Services */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h5 style={{ fontFamily: 'var(--fh)', fontSize: 14, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 2, marginBottom: 20 }}>Services</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {SVC.map(l => <a key={l} href="#services" className="flink">{l}</a>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Company */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h5 style={{ fontFamily: 'var(--fh)', fontSize: 14, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 2, marginBottom: 20 }}>Company</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {COMP.map(l => <a key={l} href="#" className="flink">{l}</a>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {/* Contact */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h5 style={{ fontFamily: 'var(--fh)', fontSize: 14, fontWeight: 700, textTransform: 'uppercase', letterSpacing: 2, marginBottom: 20 }}>Contact</h5>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {INFO.map(c => <a key={c.label} href={c.href || '#'} className="flink">{c.label}</a>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={{ marginTop: 12, display: 'inline-block', padding: '5px 14px', borderRadius: 100, fontSize: 12, fontWeight: 600, textTransform: 'uppercase', background: 'rgba(34,197,94,.12)', color: 'var(--green)', border: '1px solid rgba(34,197,94,.25)' }}>✓ EBK Registered</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingTop: 30, flexWrap: 'wrap', gap: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p style={{ fontSize: 13, color: 'var(--gray)' }}>© 2025 <span style={{ color: 'var(--yellow)' }}>Moffat Tech</span>. All rights reserved.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p style={{ fontSize: 13, color: 'var(--gray)' }}>Built with ⚡ for Kenya's energy future</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    