import { useState } from 'react';

const SERVICES = [
  { icon: '⚡', bg: 'rgba(245,196,0,.12)',   bd: 'rgba(245,196,0,.2)',   title: 'Electrical Installation', desc: 'Complete wiring, panel upgrades, and electrical system installation for residential and commercial properties.', features: ['New builds & renovations','DB board installation','Wiring & re-wiring','Load testing & certification'] },
    { icon: '☀️', bg: 'rgba(34,197,94,.12)',   bd: 'rgba(34,197,94,.2)',   title: 'Solar Panel Systems',     desc: 'Design and install grid-tied and off-grid solar energy systems to power your home or business efficiently.',  features: ['Rooftop solar installation','Battery storage systems','Solar water heating','Remote monitoring setup'] },
      { icon: '🔋', bg: 'rgba(0,200,255,.12)',   bd: 'rgba(0,200,255,.2)',   title: 'Solar Maintenance',       desc: 'Scheduled preventive maintenance, performance audits, and emergency repair for all solar installations.',     features: ['Panel cleaning & inspection','Inverter servicing','Performance optimization','System fault diagnosis'] },
        { icon: '🏭', bg: 'rgba(255,120,50,.12)',  bd: 'rgba(255,120,50,.2)',  title: 'Industrial Electrical',   desc: 'Heavy-duty electrical systems for industrial facilities, warehouses, and manufacturing plants.',              features: ['3-phase power systems','Motor control centers','Transformer installation','Safety compliance audits'] },
          { icon: '💡', bg: 'rgba(160,100,255,.12)', bd: 'rgba(160,100,255,.2)', title: 'Energy Audits',           desc: 'Detailed energy consumption analysis and recommendations to reduce your electricity bills significantly.',    features: ['Power consumption analysis','Efficiency recommendations','LED lighting upgrades','ROI projections'] },
            { icon: '🛡️', bg: 'rgba(255,80,80,.12)',   bd: 'rgba(255,80,80,.2)',   title: 'Safety & Protection',     desc: 'Surge protection, earthing systems, lightning protection, and fire alarm installation for full protection.',   features: ['Surge protection devices','Earthing & bonding','Lightning arrestors','Fire alarm systems'] },
            ];

            function ServiceCard({ s }) {
              const [hov, setHov] = useState(false);
                return (
                    <div
                          onMouseEnter={() => setHov(true)}
                                onMouseLeave={() => setHov(false)}
                                      style={{
                                              background: 'var(--dark-3)',
                                                      border: hov ? '1px solid rgba(245,196,0,.2)' : '1px solid rgba(255,255,255,.06)',
                                                              borderRadius: 12, padding: 32, transition: 'all .3s', cursor: 'pointer',
                                                                      position: 'relative', overflow: 'hidden',
                                                                              transform: hov ? 'translateY(-4px)' : 'translateY(0)',
                                                                                      boxShadow: hov ? '0 20px 40px rgba(0,0,0,.3)' : 'none',
                                                                                            }}
                                                                                                >
                                                                                                      <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: 3, background: 'var(--yellow)', transform: hov ? 'scaleX(1)' : 'scaleX(0)', transformOrigin: 'left', transition: 'transform .3s' }} />
                                                                                                            <div style={{ width: 56, height: 56, borderRadius: 14, background: s.bg, border: `1px solid ${s.bd}`, display: 'flex', alignItems: 'center', justifyContent: 'center', marginBottom: 20, fontSize: 26 }}>{s.icon}</div>
                                                                                                                  <h3 style={{ fontFamily: 'var(--fh)', fontSize: 20, fontWeight: 700, textTransform: 'uppercase', marginBottom: 10 }}>{s.title}</h3>
                                                                                                                        <p style={{ color: 'var(--gray-light)', fontSize: 14, lineHeight: 1.6, marginBottom: 20 }}>{s.desc}</p>
                                                                                                                              <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                                                                                                                                      {s.features.map(f => (
                                                                                                                                                <div key={f} style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 13, color: 'var(--gray-light)' }}>
                                                                                                                                                            <span style={{ width: 6, height: 6, background: 'var(--yellow)', borderRadius: '50%', flexShrink: 0 }} />{f}
                                                                                                                                                                      </div>
                                                                                                                                                                              ))}
                                                                                                                                                                                    </div>
                                                                                                                                                                                        </div>
                                                                                                                                                                                          );
                                                                                                                                                                                          }

                                                                                                                                                                                          export default function Services() {
                                                                                                                                                                                            return (
                                                                                                                                                                                                <>
                                                                                                                                                                                                      <style>{`
                                                                                                                                                                                                              .svc-grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 24px; }
                                                                                                                                                                                                                      @media (max-width: 1024px) { .svc-grid { grid-template-columns: repeat(2,1fr) !important; } }
                                                                                                                                                                                                                              @media (max-width: 640px)  { .svc-grid { grid-template-columns: 1fr !important; } }
                                                                                                                                                                                                                                    `}</style>
                                                                                                                                                                                                                                          <section id="services" style={{ padding: '80px 0', background: 'var(--dark-2)' }}>
                                                                                                                                                                                                                                                  <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 20px' }}>
                                                                                                                                                                                                                                                            <div style={{ fontSize: 12, fontFamily: 'var(--fh)', fontWeight: 700, letterSpacing: 4, textTransform: 'uppercase', color: 'var(--yellow)', marginBottom: 12 }}>What We Do</div>
                                                                                                                                                                                                                                                                      <h2 style={{ fontFamily: 'var(--fh)', fontSize: 'clamp(32px,6vw,52px)', fontWeight: 800, textTransform: 'uppercase', lineHeight: 1.05, marginBottom: 14 }}>
                                                                                                                                                                                                                                                                                  Professional <span style={{ color: 'var(--yellow)' }}>Electrical</span><br />& Solar Services
                                                                                                                                                                                                                                                                                            </h2>
                                                                                                                                                                                                                                                                                                      <p style={{ color: 'var(--gray-light)', fontSize: 16, fontWeight: 300, maxWidth: 520, marginBottom: 52 }}>
                                                                                                                                                                                                                                                                                                                  End-to-end engineering solutions from design to installation, maintenance, and monitoring.
                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                      <div className="svc-grid">
                                                                                                                                                                                                                                                                                                                                                  {SERVICES.map(s => <ServiceCard key={s.title} s={s} />)}
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                                                                                                                                                              </>
                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                }