import { useEffect, useRef, useState } from 'react';

const WHY_ITEMS = [
  { icon: '🏅', title: 'Certified Engineers',      desc: 'EBK-registered electrical engineers with KEBS solar certification and ongoing training.' },
    { icon: '⚡', title: 'Fast Response',             desc: 'Emergency electrical services available 24/7. We respond within 2 hours in Nairobi.'    },
      { icon: '💰', title: 'Transparent Pricing',       desc: 'No hidden charges. Get itemized quotes before any work begins. M-Pesa accepted.'         },
        { icon: '🔒', title: 'Guaranteed Workmanship',    desc: 'All installations come with a 2-year workmanship guarantee and warranty support.'         },
        ];

        const PROGRESS = [
          { label: 'Electrical Installation', pct: 97 },
            { label: 'Solar Systems',           pct: 99 },
              { label: 'Industrial Projects',     pct: 94 },
                { label: 'Client Satisfaction',     pct: 98 },
                ];

                function Bar({ label, pct, animate }) {
                  return (
                      <div>
                            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 13, color: 'var(--gray-light)', marginBottom: 6 }}>
                                    <span>{label}</span><span>{pct}%</span>
                                          </div>
                                                <div style={{ height: 6, background: 'rgba(255,255,255,.08)', borderRadius: 6, overflow: 'hidden' }}>
                                                        <div style={{ height: '100%', borderRadius: 6, background: 'linear-gradient(90deg,var(--yellow),#FFD740)', width: animate ? `${pct}%` : '0%', transition: animate ? 'width 1.2s ease' : 'none' }} />
                                                              </div>
                                                                  </div>
                                                                    );
                                                                    }

                                                                    export default function WhyUs() {
                                                                      const [animate, setAnimate] = useState(false);
                                                                        const ref = useRef(null);

                                                                          useEffect(() => {
                                                                              const obs = new IntersectionObserver(([e]) => { if (e.isIntersecting) setAnimate(true); }, { threshold: .3 });
                                                                                  if (ref.current) obs.observe(ref.current);
                                                                                      return () => obs.disconnect();
                                                                                        }, []);

                                                                                          return (
                                                                                              <>
                                                                                                    <style>{`
                                                                                                            .why-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 80px; align-items: center; }
                                                                                                                    .why-right { display: flex; justify-content: center; }
                                                                                                                            @media (max-width: 768px) {
                                                                                                                                      .why-grid  { grid-template-columns: 1fr !important; gap: 40px !important; }
                                                                                                                                                .why-right { display: none !important; }
                                                                                                                                                        }
                                                                                                                                                              `}</style>
                                                                                                                                                                    <section id="about" style={{ padding: '80px 0', background: 'var(--dark)' }}>
                                                                                                                                                                            <div style={{ maxWidth: 1100, margin: '0 auto', padding: '0 20px' }}>
                                                                                                                                                                                      <div className="why-grid">

                                                                                                                                                                                                  {/* Left */}
                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                            <div style={{ fontSize: 12, fontFamily: 'var(--fh)', fontWeight: 700, letterSpacing: 4, textTransform: 'uppercase', color: 'var(--yellow)', marginBottom: 12 }}>Why Moffat Tech</div>
                                                                                                                                                                                                                                          <h2 style={{ fontFamily: 'var(--fh)', fontSize: 'clamp(32px,6vw,52px)', fontWeight: 800, textTransform: 'uppercase', lineHeight: 1.05, marginBottom: 14 }}>
                                                                                                                                                                                                                                                          Built On <span style={{ color: 'var(--yellow)' }}>Trust</span><br />& Excellence
                                                                                                                                                                                                                                                                        </h2>
                                                                                                                                                                                                                                                                                      <p style={{ color: 'var(--gray-light)', fontSize: 16, fontWeight: 300, maxWidth: 480, marginBottom: 36 }}>
                                                                                                                                                                                                                                                                                                      With over a decade of experience, we bring certified expertise and commitment to safety to every project.
                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                                                                                                                                                                                                                                                                                                                                                  {WHY_ITEMS.map(it => (
                                                                                                                                                                                                                                                                                                                                                                    <div key={it.title} style={{ display: 'flex', gap: 18, alignItems: 'flex-start', padding: 20, background: 'var(--dark-3)', borderRadius: 12, border: '1px solid rgba(255,255,255,.05)' }}>
                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ width: 44, height: 44, background: 'rgba(245,196,0,.12)', borderRadius: 10, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, flexShrink: 0, border: '1px solid rgba(245,196,0,.2)' }}>{it.icon}</div>
                                                                                                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  <h4 style={{ fontFamily: 'var(--fh)', fontSize: 16, fontWeight: 700, textTransform: 'uppercase', marginBottom: 6 }}>{it.title}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p style={{ color: 'var(--gray)', fontSize: 13 }}>{it.desc}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {/* Right — progress card stack */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="why-right">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div ref={ref} style={{ position: 'relative', width: 320, height: 380 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ position: 'absolute', top: 0,  left: 0,  width: '100%', height: 300, background: 'var(--dark-3)', borderRadius: 16, border: '1px solid rgba(255,255,255,.08)', opacity: .4, transform: 'rotate(-4deg)', zIndex: 1 }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ position: 'absolute', top: 20, left: 10, width: '100%', height: 300, background: 'var(--dark-3)', borderRadius: 16, border: '1px solid rgba(255,255,255,.08)', opacity: .6, transform: 'rotate(-2deg)', zIndex: 2 }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ position: 'absolute', top: 40, left: 0, right: 0, zIndex: 3, background: 'var(--dark-3)', borderRadius: 16, padding: 28, border: '1px solid rgba(245,196,0,.2)', boxShadow: '0 0 40px rgba(245,196,0,.18)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ fontFamily: 'var(--fh)', fontSize: 14, fontWeight: 700, textTransform: 'uppercase', color: 'var(--gray)', letterSpacing: 1, marginBottom: 20 }}>Project Completion Rate</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {PROGRESS.map(p => <Bar key={p.label} {...p} animate={animate} />)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ marginTop: 24, display: 'flex', gap: 10, flexWrap: 'wrap' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {['✓ EBK Certified', '✓ KEBS Approved'].map(t => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span key={t} style={{ padding: '5px 14px', borderRadius: 100, fontSize: 12, fontWeight: 600, letterSpacing: 1, textTransform: 'uppercase', background: 'rgba(245,196,0,.12)', color: 'var(--yellow)', border: '1px solid rgba(245,196,0,.25)' }}>{t}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }